format_version: v1.0
configName: LED1
folderName: LED_BLINK1
frameworkPath: C:\Users\admin\Documents\1\harmony
processor: PIC32MK1024MCM064
projectName: LED_BLINK1
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MK-MC_DFP\1.11.151\atdf\PIC32MK1024MCM064.atdf
